# Default values for cp-ksql-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## Image Info
## ref: https://hub.docker.com/r/confluentinc/cp-ksql-server/
image: confluentinc/cp-ksql-server
imageTag: 5.3.1

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: IfNotPresent

## Specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecrets:

service:
  type: ClusterIP
  port: 8088
  annotations: {}

## KSQL JVM Heap Option
heapOptions: "-Xms512M -Xmx512M"

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## Custom pod annotations
podAnnotations: {}

## Pod assignment configuration
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}
affinity: {}

## Taints to tolerate on node assignment:
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Monitoring
## JMX Settings
## ref: https://docs.confluent.io/current/ksql/docs/operations.html
jmx:
  port: 5555

metrics:
  enabled: false
  agent:
    mavenUrl: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/
    version: "0.12.0"

  service:
    type: ClusterIP
    port: 5556
    annotations: {}
    labels:
      metrics: "true"

  # Enable Prometheus Operator ServiceMonitor to configure scrapping
  serviceMonitor:
    enabled: false
    # Set ServiceMontor TargetLabels to transfer labels on the Kubernetes Service onto the target.
    targetLabels: []
    # Set the namespace the ServiceMonitor should be deployed
    # namespace: monitoring
    # Set how frequently Prometheus should scrape
    # interval: 30s
    # Set path to cloudwatch-exporter telemtery-path
    # telemetryPath: /metrics
    # Set timeout for scrape
    # timeout: 10s

## Headless mode
## ref: https://docs.confluent.io/current/ksql/docs/installation/server-config/index.html
ksql:
  headless: true

## You can list load balanced service endpoint, or list of all brokers (which is hard in K8s).  e.g.:
## bootstrapServers: "PLAINTEXT://dozing-prawn-kafka-headless:9092"
kafka:
  bootstrapServers: ""

## e.g. gnoble-panther-cp-schema-registry:8081
cp-schema-registry:
  url: ""

## KSQL configuration options
## ref: https://docs.confluent.io/current/ksql/docs/installation/server-config/config-reference.html
configurationOverrides:
  {}
  # "ksql.streams.producer.retries": "2147483647"

## KSQL secret configuration options (identical to the configurationOverrides, but stores values in a secret)
## ref: https://docs.confluent.io/current/ksql/docs/installation/server-config/config-reference.html
secretConfOverrides:
  # kafkastore.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="<ACCESS_KEY>" password="<ACCESS_SECRET>";

## Additional env variables
customEnv: {}

## Extra arguments to pass the JVM
extraJavaArgs: []

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - chart-example.local

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
