{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-ksql-server.fullname" . }}-metrics
  labels:
    app: {{ template "cp-ksql-server.name" . }}
    chart: {{ template "cp-ksql-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $label, $value := .Values.metrics.service.labels }}
    {{ $label }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.metrics.service.annotations }}
  annotations: {{ toYaml .Values.metrics.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  {{ if eq .Values.metrics.service.type "LoadBalancer" -}} {{ if .Values.metrics.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
  {{ end -}}
  {{- end -}}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: 5556
  selector:
    app: {{ template "cp-ksql-server.name" . }}
    release: {{ .Release.Name }}
{{- end }}
